package com.wendigo.wave;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import net.minecraft.server.level.ServerPlayer;

import com.wendigo.plan.PlanRunner;

/**
 * Per-player memory of the wendigo's real encounters with them THIS SESSION - a narrative-continuity
 * signal for the LLM prompt (see WaveContext.toPromptText), distinct from WendigoProgressionTracker's
 * stage-derived percent. That number tells the model roughly how bold to be; this tells it what
 * actually happened across the whole run so far, so it can react ("that didn't land, try something
 * else") instead of re-deriving a plan from the number alone every request - see the plan-shape
 * collapse this was built to address (real testing converged on one near-identical template
 * regardless of severity).
 * <p>
 * A full, growing list per player, not a single "most recent" slot - the user's own explicit
 * correction to an earlier version of this class, which replaced the whole slot on every record()
 * call. That silently discarded a just-written recap the moment the NEXT encounter ended (record()
 * for encounter N+1 would overwrite encounter N's entry before any later prompt ever got a chance to
 * read its now-filled-in recap), so the model never actually saw more than one encounter back despite
 * the whole point being "the whole story for that run." record() now appends; updateRecap() finds and
 * replaces the one matching entry in place, leaving every other entry (and whatever recap they
 * already have) untouched.
 */
public final class EncounterHistory {
	private final Map<UUID, List<Entry>> byPlayer = new HashMap<>();

	/** recap is null until the model's own one-sentence narrative interpretation of THIS entry comes
	 * back (see updateRecap) - it can't be known at record() time, since that interpretation is
	 * itself generated by the NEXT plan request (the one built from this very entry's own structured
	 * facts), arriving a whole request-cycle later. WaveContext falls back to describing the raw
	 * structured facts below whenever recap is still null - typically only ever true for the newest
	 * entry in the list (every older one should already have a real recap by the time a later request
	 * reads it), but also covers a request that failed/errored before it could resolve one.
	 * <p>
	 * grabbedSuccessfully - true the moment the player is actually caught/mounted (see
	 * PlanRunner.beginForcedRide), independent of whatever happens afterward - a catch that ends in an
	 * escape still counts as having been caught. dealtDamage is the separate, narrower fact: true only
	 * when the wendigo actually landed the despawn-in-darkness damage on a still-forced rider (see
	 * PlanRunner.resolveRiderOnEnd) - a real catch can still end with dealtDamage=false if the player
	 * escaped or the wendigo never reached darkness before the ride ended. Kept as two separate
	 * booleans rather than a single tri-state so callers can't accidentally conflate "never touched
	 * them" with "touched them but they got away" the way an earlier version of this class did
	 * (grabbedSuccessfully used to only ever get set alongside the damage itself, so an escaped catch
	 * was indistinguishable from no catch at all).
	 * <p>
	 * interruptReason - the user's own explicit request to add "interruption status" alongside
	 * torchBreakCount below, since extended (also the user's own explicit request) from a bare
	 * boolean into the actual reason text: null unless this encounter ended via WendigoManager.
	 * checkForcedWaveEnd (a genuine engine-level cutoff - the player went unreachable, wandered too
	 * far, left the valid Y range, or the wendigo got stuck) rather than the plan running its own
	 * natural course (reaching its own despawn/retreat phase, or a real grab) - non-null exactly
	 * when checkForcedWaveEnd fired, holding its own returned reason string verbatim (e.g. "target
	 * too far away mid-plan (48+ blocks)"). Deliberately NOT set for a global_rule preempting the
	 * plan body, or a grab forcing a carry-flee deviation - both of those are ordinary, intended
	 * parts of how a plan can play out, not something going wrong; this field specifically captures
	 * "the engine had to step in and end this, and here's exactly why," a genuinely different, more
	 * negative signal worth telling the model about (e.g. "I lost track of them" vs "I caught them"
	 * both being legitimate but very different endings). interruptedDuringAction is the matching
	 * WHERE - whatever action type (see PlanRunner.EncounterOutcome.interruptedDuringAction) was
	 * actually in flight the instant checkForcedWaveEnd fired, or null if nothing was mid-execution
	 * right then; only meaningful alongside a non-null interruptReason. */
	public record Entry(List<String> planShape, boolean grabbedSuccessfully, boolean dealtDamage,
			boolean reachedDeadStare, boolean withdrewInstantly, int waveCount, int endTick, String recap,
			int torchBreakCount, String interruptReason, String interruptedDuringAction) {
	}

	public void record(ServerPlayer player, PlanRunner.EncounterOutcome outcome, int nowTick, String interruptReason) {
		List<Entry> entries = this.byPlayer.computeIfAbsent(player.getUUID(), id -> new ArrayList<>());
		int waveCount = entries.isEmpty() ? 1 : entries.get(entries.size() - 1).waveCount() + 1;
		entries.add(new Entry(outcome.planShape(), outcome.grabbedSuccessfully(), outcome.dealtDamage(),
			outcome.reachedDeadStare(), outcome.withdrewInstantly(), waveCount, nowTick, null,
			outcome.torchBreakCount(), interruptReason, interruptReason != null ? outcome.interruptedDuringAction() : null));
	}

	/** Called once the model's own previous_encounter_recap comes back for whichever entry was
	 * newest at the time that request was built - see this class's own record() and Entry's own doc
	 * comment. A no-op if that entry isn't found (a newer encounter already recorded and this is
	 * somehow targeting one that's since fallen out of the list - shouldn't happen in practice since
	 * lists only ever grow, but defensive all the same) - the recap describes a specific past entry,
	 * not "whatever's current now," so it's discarded rather than misattached to a different encounter
	 * than the one it was actually written about. Also a no-op for a blank recap (the model correctly
	 * reporting nothing to say, or a stale/failed request) - leaves whatever was there (null,
	 * ordinarily) alone rather than overwriting a real value with nothing. */
	public void updateRecap(ServerPlayer player, int expectedWaveCount, String recap) {
		if (recap == null || recap.isBlank()) {
			return;
		}
		List<Entry> entries = this.byPlayer.get(player.getUUID());
		if (entries == null) {
			return;
		}
		for (int i = 0; i < entries.size(); i++) {
			Entry current = entries.get(i);
			if (current.waveCount() != expectedWaveCount) {
				continue;
			}
			entries.set(i, new Entry(current.planShape(), current.grabbedSuccessfully(), current.dealtDamage(),
				current.reachedDeadStare(), current.withdrewInstantly(), current.waveCount(), current.endTick(), recap,
				current.torchBreakCount(), current.interruptReason(), current.interruptedDuringAction()));
			return;
		}
	}

	/** The most recent entry, or null if the wendigo hasn't had a real encounter with this player yet
	 * this session - WendigoManager's own target for updateRecap's waveCount (see WaveContext.
	 * previousEncounter's own doc comment for why: it's always the newest entry that still needs its
	 * recap written, every older one already has one by the time a later request would read it). */
	public Entry latest(ServerPlayer player) {
		List<Entry> entries = this.byPlayer.get(player.getUUID());
		return entries == null || entries.isEmpty() ? null : entries.get(entries.size() - 1);
	}

	/** Every real encounter with this player so far this session, oldest first - "the whole story for
	 * that run" (the user's own words), what WaveContext.toPromptText actually shows the model now
	 * instead of just the single most recent entry. Empty (never null) if there's no history yet. */
	public List<Entry> all(ServerPlayer player) {
		List<Entry> entries = this.byPlayer.get(player.getUUID());
		return entries == null ? List.of() : List.copyOf(entries);
	}
}
