"""Regenerates WendigoAnimationData.java from the Animated Java datapack export.

Usage: python3 scratchpad/convert_animation.py [path/to/wendigo-dp.zip]

If no path is given, looks for the hidden export zip Blockbench/Animated Java drops directly
into src/main/resources (named ".xdp-wendigo-dp.zip-<random>") and uses the newest one.
Reads three animations out of the datapack's per-tick mcfunction dump:
  - "stand" (frame 0 only - a static pose, not looped)  -> REST_POSE (not moving, standing hitbox)
  - "crawl" (every frame, looping)                      -> CRAWL (moving, swim hitbox)
  - "idlecrawl" (a single held frame)                    -> CRAWL_IDLE (not moving, swim hitbox)
Frame 0 of each animation must contain every bone (a full pose, not a delta) - later frames of an
animation may omit unchanged bones (delta-encoded against the previous frame), which parse_animation
already carries forward, but frame 0 itself has to be complete or there's nothing to carry forward from.
Do not edit the generated WendigoAnimationData.java by hand -- re-run this script instead.
"""
import glob
import os
import re
import sys
import zipfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESOURCES = os.path.join(REPO_ROOT, "src/main/resources")
OUTPUT = os.path.join(REPO_ROOT, "src/main/java/com/wendigo/entity/WendigoAnimationData.java")
DP_FUNCTION_ROOT = "data/wendigo/function/wendigo"

LINE_RE = re.compile(r"\$data merge entity \$\(([a-z0-9]+)\) \{\s*transformation: \[([^\]]+)\]")


def find_default_zip():
    candidates = glob.glob(os.path.join(RESOURCES, ".xdp-wendigo-dp.zip-*"))
    if not candidates:
        raise SystemExit(f"No .xdp-wendigo-dp.zip-* export found in {RESOURCES} -- pass a path explicitly.")
    return max(candidates, key=os.path.getmtime)


def parse_frame_text(text):
    bones = {}
    for line in text.splitlines():
        m = LINE_RE.search(line)
        if not m:
            continue
        bone = m.group(1)
        values = [v.strip().rstrip("f") for v in m.group(2).split(",")]
        assert len(values) == 16, f"expected 16 values, got {len(values)}: {line}"
        bones[bone] = values
    return bones


def parse_animation(zf, name):
    prefix = f"{DP_FUNCTION_ROOT}/animations/{name}/zzz/frames/"
    entries = [n for n in zf.namelist() if n.startswith(prefix) and n.endswith(".mcfunction")]
    frame_indices = sorted(int(os.path.basename(n).split(".")[0]) for n in entries)
    assert frame_indices == list(range(len(frame_indices))), f"{name}: gaps in frame sequence {frame_indices}"

    frames = []
    current = {}
    for i in frame_indices:
        delta = parse_frame_text(zf.read(f"{prefix}{i}.mcfunction").decode("utf-8"))
        current = dict(current)
        current.update(delta)
        frames.append(current)
    return frames


def fmt_matrix(values):
    return "{" + ", ".join(v + "f" for v in values) + "}"


def main():
    zip_path = sys.argv[1] if len(sys.argv) > 1 else find_default_zip()
    print(f"reading {zip_path}")
    with zipfile.ZipFile(zip_path) as zf:
        stand_frames = parse_animation(zf, "stand")
        default_pose = stand_frames[0]
        bones = list(default_pose.keys())
        crawl_frames = parse_animation(zf, "crawl")
        idlecrawl_frames = parse_animation(zf, "idlecrawl")

    for frames, name in [(crawl_frames, "crawl"), (idlecrawl_frames, "idlecrawl")]:
        for i, frame in enumerate(frames):
            missing = [b for b in bones if b not in frame]
            if missing:
                raise SystemExit(f"{name} frame {i} missing bones: {missing}")

    out = []
    out.append("package com.wendigo.entity;")
    out.append("")
    out.append("import java.util.Map;")
    out.append("import java.util.LinkedHashMap;")
    out.append("")
    out.append("/**")
    out.append(" * Generated by scratchpad/convert_animation.py from the reference Animated Java datapack export.")
    out.append(" * Do not edit by hand -- re-run the script against the dp export if the rig changes.")
    out.append(" * All matrices are row-major 4x4 affine: [r00,r01,r02,tx, r10,r11,r12,ty, r20,r21,r22,tz, 0,0,0,1].")
    out.append(" */")
    out.append("public final class WendigoAnimationData {")
    out.append(f"    public static final int CRAWL_FRAME_COUNT = {len(crawl_frames)};")
    out.append("")
    out.append("    /** Bone name -> rest-pose row-major 4x4 transform (not moving, standing hitbox). */")
    out.append("    public static final Map<String, float[]> REST_POSE = new LinkedHashMap<>();")
    out.append("")
    out.append("    /** Bone name -> per-frame row-major 4x4 transforms for the \"crawl\" (moving, swim hitbox) animation. */")
    out.append("    public static final Map<String, float[][]> CRAWL = new LinkedHashMap<>();")
    out.append("")
    out.append("    /** Bone name -> rest-pose row-major 4x4 transform for the \"crawl idle\" pose (not moving, swim hitbox). */")
    out.append("    public static final Map<String, float[]> CRAWL_IDLE = new LinkedHashMap<>();")
    out.append("")
    out.append("    static {")
    for bone in bones:
        out.append(f'        REST_POSE.put("{bone}", new float[] {fmt_matrix(default_pose[bone])});')
    out.append("")
    for bone in bones:
        out.append(f'        CRAWL_IDLE.put("{bone}", new float[] {fmt_matrix(idlecrawl_frames[0][bone])});')
    out.append("")
    for bone in bones:
        out.append(f'        CRAWL.put("{bone}", new float[][] {{')
        lines = [f"            {fmt_matrix(frame[bone])}" for frame in crawl_frames]
        out.append(",\n".join(lines))
        out.append("        });")
    out.append("    }")
    out.append("")
    out.append("    private WendigoAnimationData() {}")
    out.append("}")

    with open(OUTPUT, "w") as f:
        f.write("\n".join(out) + "\n")

    print("bones:", bones)
    print("crawl frames:", len(crawl_frames))
    print("idlecrawl frames:", len(idlecrawl_frames))
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
